import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/nav";
import ServiceProvider from "@/components/service";


const geistSans = Nunito_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin", "vietnamese"],
  weight: ["300", "600", "800"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en" suppressHydrationWarning>


      <body
        className={`${geistSans.variable}   antialiased`}
        suppressHydrationWarning
      >

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem

        >
          <ServiceProvider>
            <NavBar />
            <main className="lg:m-24  m-4  ">
              {children}
            </main>
          </ServiceProvider>
        </ThemeProvider>

      </body>

    </html>

  );
}
